// This file is managed by PhantomWP infrastructure. It will be overwritten on update. Do not edit it manually.
// Source of truth lives in PhantomWP infrastructure generators.

/**
 * PhantomWP Dev Tools
 * Auto-managed by PhantomWP infrastructure -- do not edit this file.
 * To update: use the Infrastructure modal in the PhantomWP editor.
 */

/**
 * Vite plugin: inject data-component attributes on .astro components in dev mode
 * so the IDE element inspector can identify which component file rendered each DOM element.
 * Also injects the PhantomWP iframe inspector script into every dev HTML response,
 * so the class inspector and component highlighter work even on pages that do not
 * use a PhantomWP-provided layout (e.g. imports from Claude Design).
 * Also proxies /media/cms/* requests from WordPress when files haven't been downloaded yet.
 * Only active in dev (serve) mode -- no impact on production builds.
 */
export function devComponentIdPlugin() {
    let wpConfig = null;
    let reverseMap = null;
    let wpConfigLoaded = false;

    function readDotEnvSecret(root, fs, path) {
        // .env is the single source of truth for the WP secret as of v1.25.
        // Match WP_ACCESS_SECRET=<value> (no quotes), WP_ACCESS_SECRET='<value>',
        // and WP_ACCESS_SECRET="<value>". Tolerate surrounding whitespace and
        // trailing comments after the value. Return '' (not null) when missing
        // so the media proxy can degrade gracefully without auth.
        try {
            const envPath = path.join(root, '.env');
            if (!fs.existsSync(envPath)) return '';
            const envContent = fs.readFileSync(envPath, 'utf-8');
            const lines = envContent.split(/\r?\n/);
            for (const line of lines) {
                const trimmed = line.trim();
                if (!trimmed || trimmed.startsWith('#')) continue;
                const match = trimmed.match(/^WP_ACCESS_SECRET\s*=\s*(.*)$/);
                if (!match) continue;
                let value = match[1].trim();
                // Strip a single matching pair of quotes if present.
                if (
                    (value.startsWith('"') && value.endsWith('"')) ||
                    (value.startsWith("'") && value.endsWith("'"))
                ) {
                    value = value.slice(1, -1);
                }
                return value;
            }
            return '';
        } catch {
            return '';
        }
    }

    function loadWpConfig(root, fs, path) {
        if (wpConfigLoaded) return;
        wpConfigLoaded = true;
        try {
            // Infrastructure 1.25+: WordPress URL lives in src/lib/wordpress-config.ts
            // and the secret lives ONLY in .env. Older projects (pre-1.25) have
            // everything baked into src/lib/wordpress.ts; fall through to that file
            // if the config file isn't there yet. For the secret, try .env first and
            // then fall back to whatever was baked into the config / legacy file (so
            // projects mid-migration still work).
            const configPath = path.join(root, 'src/lib/wordpress-config.ts');
            const legacyPath = path.join(root, 'src/lib/wordpress.ts');
            let wpPath = null;
            if (fs.existsSync(configPath)) wpPath = configPath;
            else if (fs.existsSync(legacyPath)) wpPath = legacyPath;
            if (!wpPath) return;
            const content = fs.readFileSync(wpPath, 'utf-8');
            const urlMatch = content.match(/(?:WORDPRESS_API_URL|WP_API_URL)\s*=\s*['"]([^'"]+)['"]/);
            if (!urlMatch) return;
            const imageSourceMatch = content.match(/IMAGE_SOURCE_MODE[^']*'(local|cdn)'/);
            if (imageSourceMatch && imageSourceMatch[1] === 'cdn') return;
            // Prefer .env, then any leftover baked-in fallback in the config file.
            // wordpress-config.ts uses JSON.stringify for the legacy fallback, so it
            // could be single- or double-quoted -- tolerate both.
            let secret = readDotEnvSecret(root, fs, path);
            if (!secret) {
                const secretMatch = content.match(/WP_ACCESS_SECRET[^|]*\|\|\s*['"]([^'"]*)['"]/);
                if (secretMatch) secret = secretMatch[1];
            }
            wpConfig = {
                siteUrl: urlMatch[1].replace(/\/wp-json.*$/, ''),
                secret: secret,
            };
        } catch { /* no config available */ }
    }

    function loadReverseMap(root, fs, path) {
        if (reverseMap) return reverseMap;
        reverseMap = {};
        try {
            const mapPath = path.join(root, 'src/lib/media-map.json');
            if (!fs.existsSync(mapPath)) return reverseMap;
            const map = JSON.parse(fs.readFileSync(mapPath, 'utf-8'));
            for (const [wpUrl, localPath] of Object.entries(map)) {
                reverseMap[localPath] = wpUrl;
            }
        } catch { /* empty map */ }
        return reverseMap;
    }

    function normalizeForLookup(filename) {
        return filename
            .replace(/-\d+x\d+(?=\.[^.]+$)/, '')
            .replace(/\.[^.]+$/, '')
            .replace(/[^a-z0-9_-]/gi, '_')
            .toLowerCase();
    }

    // The inspector script lives at .phantomwp/ide/iframe-scripts.js (outside
    // public/, so Astro does not auto-serve it). We expose it at this stable URL
    // via a Vite middleware below. Keep the URL namespaced under /_phantom/ so
    // it cannot collide with a user route.
    const INSPECTOR_SCRIPT_SRC = '/_phantom/inspector.js';
    // Pre-1.24 URL; existing parent-side message handlers identify the iframe
    // by either source, and we still tolerate references to the legacy URL when
    // checking whether a page already loads the inspector.
    const LEGACY_INSPECTOR_SCRIPT_SRC = '/__phantom_iframe_scripts.js';
    const INSPECTOR_SCRIPT_TAG =
        '<script src="' + INSPECTOR_SCRIPT_SRC + '"></script>';

    return {
        name: 'phantom-dev-tools',
        // No plugin-level enforce: the data-component injection below runs in the
        // default transform group (after enforce:'pre' plugins like Astro's
        // astro:build), which is required so that Astro's HMR sees the raw
        // .astro source — not our augmented copy — when comparing oldCode vs
        // newCode in handleHotUpdate. See the long-form comment on transform().
        apply: 'serve',
        /**
         * Ensure every dev HTML response loads the PhantomWP iframe inspector
         * script. PhantomWP's own layouts add this tag themselves, and we skip
         * injection when it's already present, so this hook only ever matters
         * for pages that bypass a PhantomWP layout (e.g. raw HTML wrapped by
         * the Claude Design importer, or ported Astro bundles with their own
         * layouts). Without it, the class inspector and component highlighter
         * have nothing to talk to inside the iframe.
         */
        transformIndexHtml: {
            order: 'post',
            handler(html) {
                if (html.indexOf(INSPECTOR_SCRIPT_SRC) !== -1) return html;
                if (html.indexOf(LEGACY_INSPECTOR_SCRIPT_SRC) !== -1) return html;
                if (html.indexOf('</body>') !== -1) {
                    return html.replace('</body>', INSPECTOR_SCRIPT_TAG + '</body>');
                }
                if (html.indexOf('</html>') !== -1) {
                    return html.replace('</html>', INSPECTOR_SCRIPT_TAG + '</html>');
                }
                return html + INSPECTOR_SCRIPT_TAG;
            },
        },
        /**
         * Inject data-component attributes into Astro's SSR-compiled JavaScript
         * (the `$$render\`...\`` template literal), NOT into the raw .astro
         * source via load().
         *
         * Why this matters: when you injected at the source level via load(),
         * Astro's astro:build transform called compile(source, filename) with
         * the augmented source and cached it as
         * astroFileToCompileMetadata.get(file).originalCode. The next time the
         * file changed, Astro's handleHotUpdate compared that augmented cached
         * source against the raw filesystem read returned by ctx.read() (which
         * goes through fs.readFile directly, not the Vite load pipeline). Those
         * two strings always differed by the inserted data-component attribute,
         * so isStyleOnlyChanged returned false. Astro then skipped the
         * "await compile(newCode, ctx.file)" call inside handleHotUpdate that
         * would have refreshed the cached CSS, but still asked Vite to invalidate
         * the virtual style module. Vite shipped an `update` message to the
         * browser, the browser re-fetched the CSS, and Astro's load handler
         * returned the *old* cached CSS for one full HMR cycle — the classic
         * "one-write-behind" stale-CSS symptom in PhantomWP's Docker dev loop.
         *
         * Running our injection in transform() (default order, i.e. after
         * Astro's enforce:'pre' transform) means Astro's compile sees the raw
         * file contents on disk, Astro's cached originalCode equals what
         * ctx.read() will later return, isStyleOnlyChanged works correctly, the
         * in-place recompile fires before Vite sends the HMR update, and the
         * browser receives fresh CSS on the very first HMR cycle.
         *
         * Astro's client-environment compile of .astro files is a stub that
         * throws and contains no $$render template; the indexOf('$$render`')
         * check below short-circuits there so we only modify SSR output.
         */
        async transform(code, id) {
            if (typeof id !== 'string') return null;
            if (id.indexOf('?') !== -1) return null;
            if (!id.endsWith('.astro')) return null;
            if (code.indexOf('data-component=') !== -1) return null;

            const srcIdx = id.indexOf('/src/');
            if (srcIdx === -1) return null;
            const relative = id.substring(srcIdx + 1);
            if (!relative.startsWith('src/components/') && !relative.startsWith('src/layouts/')) return null;

            const renderIdx = code.indexOf('$$render`');
            if (renderIdx === -1) return null;

            const slice = code.substring(renderIdx);
            const tagMatch = slice.match(/<([a-zA-Z][\w-]*)/);
            if (!tagMatch) return null;

            const insertAt = renderIdx + tagMatch.index + 1 + tagMatch[1].length;
            const attr = ' data-component="' + relative + '"';

            return {
                code: code.substring(0, insertAt) + attr + code.substring(insertAt),
                map: null,
            };
        },
        configureServer(server) {
            // Serve the iframe inspector script from .phantomwp/ide/iframe-scripts.js
            // at /_phantom/inspector.js (and at the legacy /__phantom_iframe_scripts.js
            // URL, so layouts emitted before infrastructure 1.24 keep working).
            // The file lives outside public/, so Astro's default static handler
            // does not pick it up.
            server.middlewares.use(async (req, res, next) => {
                if (!req.url) return next();
                const urlPath = req.url.split('?')[0];
                if (urlPath !== INSPECTOR_SCRIPT_SRC && urlPath !== LEGACY_INSPECTOR_SCRIPT_SRC) return next();
                const fs = await import('node:fs');
                const path = await import('node:path');
                const filePath = path.join(server.config.root, '.phantomwp', 'ide', 'iframe-scripts.js');
                if (!fs.existsSync(filePath)) return next();
                try {
                    const body = await fs.promises.readFile(filePath);
                    res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
                    res.setHeader('Cache-Control', 'no-cache');
                    res.end(body);
                } catch {
                    return next();
                }
            });

            server.middlewares.use(async (req, res, next) => {
                if (!req.url || !req.url.startsWith('/media/cms/')) return next();

                const fs = await import('node:fs');
                const path = await import('node:path');
                const root = server.config.root;
                loadWpConfig(root, fs, path);
                if (!wpConfig) return next();

                const requestedPath = req.url.split('?')[0];

                const publicFile = path.join(root, 'public', requestedPath);
                if (fs.existsSync(publicFile)) return next();

                const srcFile = path.join(root, 'src', requestedPath.replace('/media/cms/', 'media/cms/'));
                if (fs.existsSync(srcFile)) return next();

                const rMap = loadReverseMap(root, fs, path);
                let wpUrl = rMap[requestedPath];

                if (!wpUrl) {
                    const filename = requestedPath.split('/').pop() || '';
                    const normalized = normalizeForLookup(filename);
                    for (const [localPath, remoteUrl] of Object.entries(rMap)) {
                        const localFilename = localPath.split('/').pop() || '';
                        if (normalizeForLookup(localFilename) === normalized) {
                            wpUrl = remoteUrl;
                            break;
                        }
                    }
                }

                if (!wpUrl) {
                    const filename = requestedPath.split('/').pop() || '';
                    const searchName = filename
                        .replace(/\.webp$/, '')
                        .replace(/[_-]/g, ' ')
                        .trim();
                    try {
                        const headers = { 'Accept': 'application/json' };
                        if (wpConfig.secret) headers['X-PhantomWP-Secret'] = wpConfig.secret;
                        const searchUrl = wpConfig.siteUrl + '/wp-json/wp/v2/media?search=' + encodeURIComponent(searchName) + '&per_page=10';
                        const searchRes = await fetch(searchUrl, { headers });
                        if (searchRes.ok) {
                            const items = await searchRes.json();
                            const normalizedReq = normalizeForLookup(filename);
                            for (const item of items) {
                                if (!item.source_url) continue;
                                const itemFilename = item.source_url.split('/').pop() || '';
                                if (normalizeForLookup(itemFilename) === normalizedReq) {
                                    wpUrl = item.source_url;
                                    break;
                                }
                            }
                            if (!wpUrl && items.length > 0 && items[0].source_url) {
                                wpUrl = items[0].source_url;
                            }
                        }
                    } catch { /* search failed, fall through */ }
                }

                if (!wpUrl) return next();

                try {
                    const headers = {};
                    if (wpConfig.secret) headers['X-PhantomWP-Secret'] = wpConfig.secret;
                    const imgRes = await fetch(wpUrl, { headers });
                    if (!imgRes.ok) return next();

                    const contentType = imgRes.headers.get('content-type') || 'image/jpeg';
                    res.setHeader('Content-Type', contentType);
                    res.setHeader('Cache-Control', 'public, max-age=86400');
                    res.setHeader('X-Proxied-From', 'wordpress');

                    const buffer = Buffer.from(await imgRes.arrayBuffer());
                    res.end(buffer);
                } catch {
                    return next();
                }
            });
        },
    };
}
